# Generated by Django 6.1 on 2026-09-02 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(db_column='IdCategoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='IdCliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Apellido', max_length=100)),
                ('telefono', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Telefono', max_length=30)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='EstadoNegocio',
            fields=[
                ('idestado', models.AutoField(db_column='IdEstado', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=100)),
            ],
            options={
                'db_table': 'EstadoNegocio',
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('idestadopedido', models.AutoField(db_column='IdEstado', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=100)),
            ],
            options={
                'db_table': 'EstadoPedido',
            },
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('idestado', models.AutoField(db_column='IdEstado', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=100)),
            ],
            options={
                'db_table': 'EstadoProducto',
            },
        ),
        migrations.CreateModel(
            name='EstadoStock',
            fields=[
                ('idestado', models.AutoField(db_column='IdEstado', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=100)),
                ('nivelcritico', models.IntegerField(db_column='NivelCritico', default=5)),
            ],
            options={
                'db_table': 'EstadoStock',
            },
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('idextra', models.AutoField(db_column='IdExtra', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'Extras',
            },
        ),
        migrations.CreateModel(
            name='GrupoOpcion',
            fields=[
                ('idgrupo', models.AutoField(db_column='IdGrupo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('min_selecciones', models.IntegerField(db_column='MinSelecciones', default=0)),
                ('max_selecciones', models.IntegerField(db_column='MaxSelecciones', default=1)),
            ],
            options={
                'db_table': 'GrupoOpcion',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('idinsumo', models.AutoField(db_column='IdInsumo', primary_key=True, serialize=False)),
                ('nombreinsumo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='NombreInsumo', max_length=100)),
                ('unidadmedida', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='UnidadMedida', max_length=30)),
                ('stockactual', models.DecimalField(db_column='StockActual', decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'Insumo',
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('idmediopago', models.AutoField(db_column='IdMedioPago', primary_key=True, serialize=False)),
                ('nombremetodo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], db_collation='Modern_Spanish_CI_AS', db_column='NombreMetodo', max_length=50)),
            ],
            options={
                'db_table': 'MedioPago',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(db_column='IdRol', primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='NombreRol', max_length=50)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('iddireccion', models.AutoField(db_column='IdDireccion', primary_key=True, serialize=False)),
                ('calle', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Calle', max_length=150)),
                ('numero', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Numero', max_length=20)),
                ('piso', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Piso', max_length=20, null=True)),
                ('localidad', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Localidad', max_length=100)),
                ('idcliente', models.ForeignKey(db_column='IdCliente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='direcciones', to='core.cliente')),
            ],
            options={
                'db_table': 'Direccion',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idcompra', models.AutoField(db_column='IdCompra', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('cantidad', models.DecimalField(db_column='Cantidad', decimal_places=2, max_digits=10)),
                ('preciototal', models.DecimalField(db_column='PrecioTotal', decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(db_column='IdInsumo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.insumo')),
            ],
            options={
                'db_table': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('idnegocio', models.AutoField(db_column='IdNegocio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('telefono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Telefono', max_length=30, null=True)),
                ('idestado', models.ForeignKey(db_column='IdEstado', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadonegocio')),
            ],
            options={
                'db_table': 'Negocio',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idhorario', models.AutoField(db_column='IdHorario', primary_key=True, serialize=False)),
                ('diasemana', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='DiaSemana', max_length=50)),
                ('horaapertura', models.TimeField(db_column='HoraApertura')),
                ('horacierre', models.TimeField(db_column='HoraCierre')),
                ('idnegocio', models.ForeignKey(blank=True, db_column='IdNegocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.negocio')),
            ],
            options={
                'db_table': 'Horario',
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('idopcion', models.AutoField(db_column='IdOpcion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('precio_adicional', models.DecimalField(db_column='PrecioAdicional', decimal_places=2, default=0.0, max_digits=10)),
                ('idgrupo', models.ForeignKey(blank=True, db_column='IdGrupo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.grupoopcion')),
            ],
            options={
                'db_table': 'Opcion',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=255, null=True)),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10)),
                ('imagen', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Imagen', max_length=255, null=True)),
                ('estadoproducto', models.ForeignKey(blank=True, db_column='IdEstadoProducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadoproducto')),
                ('estadostock', models.ForeignKey(blank=True, db_column='IdEstadoStock', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadostock')),
                ('idcategoria', models.ForeignKey(blank=True, db_column='IdCategoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
                ('idnegocio', models.ForeignKey(blank=True, db_column='IdNegocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.negocio')),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idpromocion', models.AutoField(db_column='IdPromocion', primary_key=True, serialize=False)),
                ('palabraclave', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='PalabraClave', max_length=50)),
                ('tipobeneficio', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='TipoBeneficio', max_length=50)),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=2, max_digits=10)),
                ('minimocompra', models.DecimalField(db_column='MinimoCompra', decimal_places=2, default=0.0, max_digits=10)),
                ('activo', models.IntegerField(db_column='Activo', default=1)),
                ('idproducto', models.ForeignKey(blank=True, db_column='IdProducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'db_table': 'Promocion',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(db_column='IdPedido', primary_key=True, serialize=False)),
                ('horarioentregadeseado', models.DateTimeField(blank=True, db_column='HorarioEntregaDeseado', null=True)),
                ('justificacioncancelacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='JustificacionCancelacion', max_length=255, null=True)),
                ('cantidad', models.IntegerField(db_column='Cantidad', default=1)),
                ('idcliente', models.ForeignKey(blank=True, db_column='IdCliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
                ('idestadopedido', models.ForeignKey(blank=True, db_column='IdEstadoPedido', default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadopedido')),
                ('idmediopago', models.ForeignKey(blank=True, db_column='IdMedioPago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.mediopago')),
                ('producto', models.ForeignKey(blank=True, db_column='IdProducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
                ('idpromocion', models.ForeignKey(blank=True, db_column='IdPromocion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.promocion')),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idreceta', models.AutoField(db_column='IdReceta', primary_key=True, serialize=False)),
                ('cantidadinsumo', models.DecimalField(db_column='CantidadInsumo', decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(db_column='IdInsumo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.insumo')),
                ('producto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'db_table': 'Receta',
            },
        ),
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('idredsocial', models.AutoField(db_column='IdRedSocial', primary_key=True, serialize=False)),
                ('plataforma', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Plataforma', max_length=50)),
                ('enlace', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Enlace', max_length=255)),
                ('idnegocio', models.ForeignKey(blank=True, db_column='IdNegocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.negocio')),
            ],
            options={
                'db_table': 'RedesSociales',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.AutoField(db_column='IdEmpleado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Apellido', max_length=100)),
                ('contrasena', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Contrasena', max_length=255)),
                ('idnegocio', models.ForeignKey(blank=True, db_column='IdNegocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.negocio')),
                ('rol', models.ForeignKey(db_column='IdRol', on_delete=django.db.models.deletion.DO_NOTHING, to='core.rol')),
            ],
            options={
                'db_table': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='UltimaModificacion',
            fields=[
                ('idmodificacion', models.AutoField(db_column='IdModificacion', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('descripcioncambio', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='DescripcionCambio', max_length=255, null=True)),
                ('empleado', models.ForeignKey(db_column='IdEmpleado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
                ('idestado', models.ForeignKey(db_column='IdEstado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadonegocio')),
            ],
            options={
                'db_table': 'UltimaModificacion',
            },
        ),
        migrations.CreateModel(
            name='ZonasEntrega',
            fields=[
                ('idzona', models.AutoField(db_column='IdZona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('costoEnvio', models.DecimalField(db_column='CostoEnvio', decimal_places=2, default=0.0, max_digits=10)),
                ('idnegocio', models.ForeignKey(blank=True, db_column='IdNegocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.negocio')),
            ],
            options={
                'db_table': 'ZonasEntrega',
            },
        ),
        migrations.CreateModel(
            name='ProductoExtras',
            fields=[
                ('id_producto_extra', models.AutoField(db_column='IdProductoExtra', primary_key=True, serialize=False)),
                ('idextra', models.ForeignKey(blank=True, db_column='IdExtra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.extras')),
                ('idproducto', models.ForeignKey(blank=True, db_column='IdProducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'db_table': 'ProductoExtras',
                'unique_together': {('idproducto', 'idextra')},
            },
        ),
        migrations.CreateModel(
            name='ProductoGrupoOpcion',
            fields=[
                ('id_producto_grupo', models.AutoField(db_column='IdProductoGrupo', primary_key=True, serialize=False)),
                ('idgrupo', models.ForeignKey(blank=True, db_column='IdGrupo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.grupoopcion')),
                ('idproducto', models.ForeignKey(blank=True, db_column='IdProducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'db_table': 'ProductoGrupoOpcion',
                'unique_together': {('idproducto', 'idgrupo')},
            },
        ),
    ]
