# Generated by Django 6.1 on 2026-08-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(db_column='IdCategoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
            ],
            options={
                'db_table': 'Categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoOpcion',
            fields=[
                ('idgrupo', models.AutoField(db_column='IdGrupo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('min_selecciones', models.IntegerField(db_column='MinSelecciones', default=0)),
                ('max_selecciones', models.IntegerField(db_column='MaxSelecciones', default=1)),
            ],
            options={
                'db_table': 'GrupoOpcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('idopcion', models.AutoField(db_column='IdOpcion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('precio_adicional', models.DecimalField(db_column='PrecioAdicional', decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'Opcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=255, null=True)),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoGrupoOpcion',
            fields=[
                ('id', models.AutoField(db_column='IdProductoGrupo', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ProductoGrupoOpcion',
                'managed': False,
            },
        ),
    ]
