# Generated by Django 6.1 on 2026-09-11 22:52

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('idcategoria', models.AutoField(db_column='IdCategoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
            ],
            options={
                'db_table': 'CategoriaProducto',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='IdCliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Apellido', max_length=100)),
                ('telefono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Telefono', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.AutoField(db_column='IdEmpleado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Apellido', max_length=100)),
                ('contrasena', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Contrasena', max_length=255)),
            ],
            options={
                'db_table': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='EstadoNegocio',
            fields=[
                ('idestado', models.AutoField(db_column='IdEstado', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=250, null=True)),
            ],
            options={
                'db_table': 'EstadoNegocio',
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('idestado', models.AutoField(db_column='IdEstado', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=50)),
            ],
            options={
                'db_table': 'EstadoPedido',
            },
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('idestado', models.AutoField(db_column='IdEstado', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=50)),
            ],
            options={
                'db_table': 'EstadoProducto',
            },
        ),
        migrations.CreateModel(
            name='EstadoStock',
            fields=[
                ('idestado', models.AutoField(db_column='IdEstado', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=10, null=True)),
                ('nivelcritico', models.DecimalField(blank=True, db_column='NivelCritico', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'EstadoStock',
            },
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('idextra', models.AutoField(db_column='IdExtra', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Extras',
            },
        ),
        migrations.CreateModel(
            name='GrupoOpcion',
            fields=[
                ('idgrupo', models.AutoField(db_column='IdGrupo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('minselecciones', models.IntegerField(blank=True, db_column='MinSelecciones', null=True)),
                ('maxselecciones', models.IntegerField(blank=True, db_column='MaxSelecciones', null=True)),
            ],
            options={
                'db_table': 'GrupoOpcion',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('idinsumo', models.AutoField(db_column='IdInsumo', primary_key=True, serialize=False)),
                ('nombreinsumo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='NombreInsumo', max_length=100)),
                ('unidadmedidaingreso', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='UnidadMedidaIngreso', max_length=30)),
                ('unidadmedidaegreso', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='UnidadMedidaEgreso', max_length=30)),
                ('stockactual', models.DecimalField(db_column='StockActual', decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'Insumo',
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('idmediopago', models.AutoField(db_column='IdMedioPago', primary_key=True, serialize=False)),
                ('nombremetodo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='NombreMetodo', max_length=50)),
            ],
            options={
                'db_table': 'MedioPago',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idpromocion', models.AutoField(db_column='IdPromocion', primary_key=True, serialize=False)),
                ('palabraclave', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='PalabraClave', max_length=50, null=True)),
                ('tipobeneficio', models.CharField(blank=True, choices=[('2x1', '2 x 1'), ('3x2', '3 x 2'), ('PRODUCTO_GRATIS', 'Producto gratis'), ('DESCUENTO_PORCENTAJE', 'Descuento porcentual'), ('DESCUENTO_FIJO', 'Descuento fijo')], db_collation='Modern_Spanish_CI_AS', db_column='TipoBeneficio', max_length=50, null=True)),
                ('valor', models.DecimalField(blank=True, db_column='Valor', decimal_places=2, max_digits=10, null=True)),
                ('fechainicio', models.DateField(blank=True, db_column='FechaInicio', null=True)),
                ('fechafin', models.DateField(blank=True, db_column='FechaFin', null=True)),
                ('activo', models.IntegerField(blank=True, db_column='Activo', default=1, null=True)),
            ],
            options={
                'db_table': 'Promocion',
            },
        ),
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('idredsocial', models.AutoField(db_column='IdRedSocial', primary_key=True, serialize=False)),
                ('plataforma', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Plataforma', max_length=50, null=True)),
                ('enlace', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Enlace', max_length=250, null=True)),
                ('idnegocio', models.IntegerField(blank=True, db_column='IdNegocio', null=True)),
            ],
            options={
                'db_table': 'RedesSociales',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(db_column='IdRol', primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='NombreRol', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='ZonasEntrega',
            fields=[
                ('idzona', models.AutoField(db_column='IdZona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50, null=True)),
                ('costoenvio', models.DecimalField(blank=True, db_column='CostoEnvio', decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('idnegocio', models.IntegerField(blank=True, db_column='IdNegocio', null=True)),
            ],
            options={
                'db_table': 'ZonasEntrega',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('iddireccion', models.AutoField(db_column='IdDireccion', primary_key=True, serialize=False)),
                ('calle', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Calle', max_length=150)),
                ('numero', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Numero', max_length=20)),
                ('piso', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Piso', max_length=10, null=True)),
                ('localidad', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Localidad', max_length=100)),
                ('idcliente', models.ForeignKey(blank=True, db_column='IdCliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='direcciones', to='core.cliente')),
            ],
            options={
                'db_table': 'Direccion',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idcompra', models.AutoField(db_column='IdCompra', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('preciototal', models.DecimalField(db_column='PrecioTotal', decimal_places=2, max_digits=10)),
                ('idempleado', models.ForeignKey(blank=True, db_column='IdEmpleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
            ],
            options={
                'db_table': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('iddetallecompra', models.AutoField(db_column='IdDetalleCompra', primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(db_column='Cantidad', decimal_places=2, max_digits=10)),
                ('costounitario', models.DecimalField(db_column='CostoUnitario', decimal_places=2, max_digits=10)),
                ('idcompra', models.ForeignKey(blank=True, db_column='IdCompra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.compras')),
                ('idinsumo', models.ForeignKey(blank=True, db_column='IdInsumo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.insumo')),
            ],
            options={
                'db_table': 'DetalleCompra',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('idnegocio', models.AutoField(db_column='IdNegocio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('telefono', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Telefono', max_length=30)),
                ('idempleado', models.ForeignKey(blank=True, db_column='IdEmpleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
                ('idestado', models.ForeignKey(blank=True, db_column='IdEstado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadonegocio')),
                ('idredsocial', models.ForeignKey(blank=True, db_column='IdRedSocial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.redessociales')),
                ('idzona', models.ForeignKey(blank=True, db_column='IdZona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.zonasentrega')),
            ],
            options={
                'db_table': 'Negocio',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idhorario', models.AutoField(db_column='IdHorario', primary_key=True, serialize=False)),
                ('diasemana', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='DiaSemana', max_length=20, null=True)),
                ('horaapertura', models.TimeField(blank=True, db_column='HoraApertura', null=True)),
                ('horacierre', models.TimeField(blank=True, db_column='HoraCierre', null=True)),
                ('estaabierto', models.IntegerField(blank=True, db_column='EstaAbierto', null=True)),
                ('idnegocio', models.ForeignKey(blank=True, db_column='IdNegocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.negocio')),
            ],
            options={
                'db_table': 'Horario',
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('idopcion', models.AutoField(db_column='IdOpcion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('precioadicional', models.DecimalField(blank=True, db_column='PrecioAdicional', decimal_places=2, max_digits=10, null=True)),
                ('idgrupo', models.ForeignKey(blank=True, db_column='IdGrupo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.grupoopcion')),
            ],
            options={
                'db_table': 'Opcion',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(db_column='IdPedido', primary_key=True, serialize=False)),
                ('horarioentregadeseado', models.TimeField(blank=True, db_column='HorarioEntregaDeseado', null=True)),
                ('justificacioncancelacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='JustificacionCancelacion', max_length=250, null=True)),
                ('idpromocion', models.IntegerField(blank=True, db_column='IdPromocion', null=True)),
                ('idproducto', models.IntegerField(blank=True, db_column='IdProducto', null=True)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('idcliente', models.ForeignKey(blank=True, db_column='IdCliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
                ('idestadopedido', models.ForeignKey(blank=True, db_column='IdEstadoPedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadopedido')),
                ('idmediopago', models.ForeignKey(blank=True, db_column='IdMedioPago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.mediopago')),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(blank=True, db_column='Descripcion', null=True, verbose_name='Descripcion')),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, db_column='Imagen', max_length=2000, null=True, upload_to='productos/')),
                ('idcategoria', models.ForeignKey(blank=True, db_column='IdCategoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoriaproducto')),
                ('idestadoproducto', models.ForeignKey(blank=True, db_column='IdEstadoProducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadoproducto')),
                ('idestadostock', models.ForeignKey(blank=True, db_column='IdEstadoStock', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadostock')),
                ('idnegocio', models.ForeignKey(blank=True, db_column='IdNegocio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.negocio')),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('iddetallepedido', models.AutoField(db_column='IdDetallePedido', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('preciounitario', models.DecimalField(db_column='PrecioUnitario', decimal_places=2, max_digits=10)),
                ('idpedido', models.ForeignKey(blank=True, db_column='IdPedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.pedido')),
                ('idproducto', models.ForeignKey(blank=True, db_column='IdProducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'db_table': 'DetallePedido',
            },
        ),
        migrations.CreateModel(
            name='ProductoExtras',
            fields=[
                ('idproductoextra', models.AutoField(db_column='IdProductoExtra', primary_key=True, serialize=False)),
                ('idextra', models.ForeignKey(db_column='IdExtra', on_delete=django.db.models.deletion.DO_NOTHING, to='core.extras')),
                ('idproducto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'db_table': 'ProductoExtras',
            },
        ),
        migrations.CreateModel(
            name='ProductoGrupoOpcion',
            fields=[
                ('idproductogrupo', models.AutoField(db_column='IdProductoGrupo', primary_key=True, serialize=False)),
                ('idgrupo', models.ForeignKey(blank=True, db_column='IdGrupo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.grupoopcion')),
                ('idproducto', models.ForeignKey(blank=True, db_column='IdProducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'db_table': 'ProductoGrupoOpcion',
            },
        ),
        migrations.CreateModel(
            name='ProductoPromocion',
            fields=[
                ('idproductopromocion', models.AutoField(db_column='IdProductoPromocion', primary_key=True, serialize=False)),
                ('idproducto', models.ForeignKey(blank=True, db_column='IdProducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
                ('idpromocion', models.ForeignKey(blank=True, db_column='IdPromocion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.promocion')),
            ],
            options={
                'db_table': 'ProductoPromocion',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idreceta', models.AutoField(db_column='IdReceta', primary_key=True, serialize=False)),
                ('idinsumo', models.IntegerField(blank=True, db_column='IdInsumo', null=True)),
                ('idproducto', models.ForeignKey(blank=True, db_column='IdProducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'db_table': 'Receta',
            },
        ),
        migrations.CreateModel(
            name='RecetaInsumo',
            fields=[
                ('idrecetainsumo', models.IntegerField(db_column='IdRecetaInsumo', primary_key=True, serialize=False)),
                ('cantidadinsumo', models.IntegerField(db_column='CantidadInsumo')),
                ('idinsumo', models.ForeignKey(blank=True, db_column='IdInsumo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.insumo')),
                ('idreceta', models.ForeignKey(blank=True, db_column='IdReceta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.receta')),
            ],
            options={
                'db_table': 'RecetaInsumo',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='idrol',
            field=models.ForeignKey(blank=True, db_column='IdRol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.rol'),
        ),
        migrations.CreateModel(
            name='UltimaModificacion',
            fields=[
                ('idmodificacion', models.AutoField(db_column='IdModificacion', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('descripcioncambio', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='DescripcionCambio', max_length=250, null=True)),
                ('idnegocio', models.IntegerField(blank=True, db_column='IdNegocio', null=True)),
                ('idempleado', models.ForeignKey(blank=True, db_column='IdEmpleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
            ],
            options={
                'db_table': 'UltimaModificacion',
            },
        ),
        migrations.AddField(
            model_name='estadonegocio',
            name='idmodificacion',
            field=models.ForeignKey(db_column='IdModificacion', on_delete=django.db.models.deletion.DO_NOTHING, to='core.ultimamodificacion'),
        ),
    ]
