# Generated by Django 6.1 on 2026-09-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, db_column='Imagen', max_length=255, null=True, upload_to='productos/'),
        ),
    ]
