# Generated by Django 6.1 on 2026-08-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='grupoopcion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='opcion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productogrupoopcion',
            options={'managed': True},
        ),
    ]
