# Generated by Django 6.1 on 2026-09-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetainsumo',
            name='es_removible',
            field=models.BooleanField(default=False),
        ),
    ]
