# Generated by Django 6.1 on 2026-09-06 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBeneficio',
            fields=[
                ('idtipobeneficio', models.AutoField(db_column='IdTipoBeneficio', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=30, unique=True)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=250, null=True)),
            ],
            options={
                'db_table': 'TipoBeneficio',
            },
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='tipobeneficio',
        ),
        migrations.AddField(
            model_name='promocion',
            name='idcategoria',
            field=models.ForeignKey(blank=True, db_column='IdCategoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='promociones', to='core.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='idproducto',
            field=models.ForeignKey(blank=True, db_column='IdProducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='promociones_directas', to='core.producto'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='activo',
            field=models.BooleanField(db_column='Activo', default=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='idtipobeneficio',
            field=models.ForeignKey(blank=True, db_column='IdTipoBeneficio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='promociones', to='core.tipobeneficio'),
        ),
    ]
