# Generated by Django 6.1 on 2026-08-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoria_options_alter_grupoopcion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grupoopcion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='opcion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productogrupoopcion',
            options={'managed': False},
        ),
    ]
