# Generated by Django 6.1 on 2026-09-17 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recetainsumo_es_removible'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stockminimo',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
                ('idajuste', models.AutoField(db_column='IdAjuste', primary_key=True, serialize=False)),
                ('cantidadanterior', models.DecimalField(db_column='CantidadAnterior', decimal_places=2, max_digits=10)),
                ('cantidadnueva', models.DecimalField(db_column='CantidadNueva', decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Motivo', max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='Fecha')),
                ('idinsumo', models.ForeignKey(db_column='IdInsumo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.insumo')),
            ],
            options={
                'db_table': 'AjusteStock',
            },
        ),
    ]
