# Generated by Django 6.1 on 2026-09-06 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipobeneficio_delete_categoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='idtipobeneficio',
        ),
        migrations.RemoveField(
            model_name='productopromocion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='idcategoria',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='idproducto',
        ),
        migrations.AddField(
            model_name='promocion',
            name='tipobeneficio',
            field=models.CharField(blank=True, choices=[('2x1', '2 x 1'), ('3x2', '3 x 2'), ('PRODUCTO_GRATIS', 'Producto gratis'), ('DESCUENTO_PORCENTAJE', 'Descuento porcentual'), ('DESCUENTO_FIJO', 'Descuento fijo')], db_collation='Modern_Spanish_CI_AS', db_column='TipoBeneficio', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estadonegocio',
            name='idmodificacion',
            field=models.ForeignKey(db_column='IdModificacion', default='unidades', on_delete=django.db.models.deletion.DO_NOTHING, to='core.ultimamodificacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidadmedidaegreso',
            field=models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='UnidadMedidaEgreso', default='unidades', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidadmedidaingreso',
            field=models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='UnidadMedidaIngreso', default='unidades', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productopromocion',
            name='idproductopromocion',
            field=models.AutoField(db_column='IdProductoPromocion', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocion',
            name='activo',
            field=models.IntegerField(blank=True, db_column='Activo', default=1, null=True),
        ),
        migrations.DeleteModel(
            name='TipoBeneficio',
        ),
    ]
