# Generated by Django 6.1 on 2026-09-03 00:57

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, db_column='Descripcion', null=True, verbose_name='Descripcion'),
        ),
    ]
