# Generated by Django 6.1 on 2026-08-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categoria_options_alter_grupoopcion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('idextra', models.AutoField(db_column='IdExtra', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'Extras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoExtras',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ProductoExtras',
                'managed': False,
            },
        ),
    ]
