# Generated by Django 6.1 on 2026-09-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_insumo_codigo_insumo_stockminimo_ajustestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True),
        ),
    ]
