# Generated by Django 6.1 on 2026-08-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_extras_productoextras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='extras',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grupoopcion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='opcion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productoextras',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productogrupoopcion',
            options={},
        ),
    ]
