# Generated by Django 6.1 on 2026-09-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido_pagado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='idproducto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(blank=True, db_column='Total', decimal_places=2, max_digits=10, null=True),
        ),
    ]
