# Generated by Django 6.1 on 2026-09-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pedido_cantidad_remove_pedido_idproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBeneficio',
            fields=[
                ('idtipobeneficio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('comportamiento', models.CharField(choices=[('SIN_VALOR', 'Sin valor (Ej: 2x1, 3x2)'), ('PORCENTAJE', 'Descuento porcentual (%)'), ('MONTO_FIJO', 'Descuento en dinero fijo ($)')], default='SIN_VALOR', max_length=50, verbose_name='Comportamiento')),
            ],
        ),
        migrations.AlterModelOptions(
            name='promocion',
            options={'managed': False},
        ),
    ]
