# Generated by Django 6.1 on 2026-09-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tipobeneficio_alter_promocion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'managed': False},
        ),
    ]
