# Generated by Django 6.1 on 2026-09-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_detallepedido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipobeneficio',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tipobeneficio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tipobeneficio',
            name='comportamiento',
            field=models.CharField(choices=[('PORCENTAJE', 'Descuento porcentual (%)'), ('MONTO_FIJO', 'Descuento en dinero fijo ($)'), ('SIN_VALOR', 'Sin valor (Ej: 2x1, Producto de regalo)')], default='SIN_VALOR', max_length=50, verbose_name='Comportamiento'),
        ),
    ]
