# Generated by Django 6.1 on 2026-09-30 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tipobeneficio_codigo_tipobeneficio_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipobeneficio',
            options={'managed': False},
        ),
    ]
