# Generated by Django 6.1 on 2026-09-30 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_tipobeneficio_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipobeneficio',
            table='TipoBeneficio',
        ),
    ]
