# Generated by Django 6.1 on 2026-10-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tipobeneficio_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetainsumo',
            name='cantidadinsumo',
            field=models.IntegerField(blank=True, db_column='CantidadInsumo', default=0, null=True),
        ),
    ]
